### ISSUE TITLE
Stop using Guild#defaultChannel

### ISSUE THREAD

**Issue by MyNameIsKir** [MyNameIsKir/Downtime-Discord-Bot#11]
Discord.js depreciated Guild#defaultChannel, and so we need to stop using it (Used in the join/leave messages). It will be removed in v12.0.0 of discord.js and I suspect that we'll want to upgrade when that time comes.

**Comment by Tortenschachtel** [comment]
Since Discord has its own welcome mesages now do we still need these?
If we do i suggest using the systemChannel, which is the channel welcome messages are written to. The channel can be set in the server settings any may be null.
